In [1]:
import numpy as np

In [2]:
X = np.array([[0,0], [0,1], [1,0], [1,1]])
Y = np.array([[0, 0, 0, 1]]).T
X.shape, Y.shape

((4, 2), (4, 1))

In [3]:
def sig(z):
    return 1/(1 + np.exp(-z))

In [4]:
def derivativeSig(z):
    return sig(z) * (1 - sig(z))

In [5]:
# No hidden layer weights
weights = 2 * np.random.random((2,1)) - 1
bias = 2 * np.random.random(1) - 1
learning_rate = 0.1
weights, bias

(array([[-0.1815758 ],
        [-0.57594442]]),
 array([0.48319675]))

## A Simple Neural Network with re-iterating Backward propagation


In [6]:
# Forward propagation without any hidden layer
# Backward propagation is done with a number of iterations while pushing the error using gradient descent
for _ in range(10000):
    output0 = X
    output = sig(np.dot(output0, weights) + bias)

    first_term = output - Y
    input_for_last_layer = np.dot(output0, weights) + bias
    second_term = derivativeSig(input_for_last_layer)
    first_two = first_term * second_term
    first_two.shape

    changes = np.array([[0.0], [0.0]])

    for i in range(2):
        for j in range(4):
            changes[i][0] += first_two[j][0] * output0[j][i]

    weights = weights - learning_rate * changes
    bias_change = 0.0
    for j in range(4):
        bias_change += first_two[j][0] * 1
    bias = bias - learning_rate * bias_change

output = sig(np.dot(X, weights) + bias)
weights, bias, output

(array([[5.47058096],
        [5.47058096]]),
 array([-8.29860294]),
 array([[2.48802343e-04],
        [5.58285709e-02],
        [5.58285711e-02],
        [9.33550883e-01]]))