In [1]:
import numpy as np

In [2]:
X = np.array([[0,0], [0,1], [1,0], [1,1]])
Y = np.array([[0, 0, 0, 1]]).T
X.shape, Y.shape

((4, 2), (4, 1))

In [3]:
def sig(z):
    return 1/(1 + np.exp(-z))

In [4]:
# No hidden layer weights
weights = 2 * np.random.random((2,1)) - 1
bias = 2 * np.random.random(1) - 1
weights, bias

(array([[ 0.29748702],
        [-0.65071834]]),
 array([-0.09897256]))

In [5]:
# Forward propagation without any hidden layer
output0 = X
output = sig(np.dot(output0, weights) + bias)
output

array([[0.47527704],
       [0.32088866],
       [0.54946627],
       [0.3888369 ]])

In [6]:
wh = 2 * np.random.random((2,2)) - 1  # Hidden layer weights randomized
bh = 2 * np.random.random((1,2)) - 1  # Hidden layer biased randomized
wo = 2 * np.random.random((2,1)) - 1
bo = 2 * np.random.random((1,1)) - 1

In [7]:
output0 = X 
outputHidden = sig(np.dot(output0, wh) + bh)
output = sig(np.dot(outputHidden, wo) + bo)
output

array([[0.50960617],
       [0.48747927],
       [0.54257702],
       [0.51731811]])